charset: utf-8
template: "template_toolkit"
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'
        ENCODE: utf8

#logger: "Log4perl"
#log4perl_conf: log4perl.conf

supported_versions:
   - 1.1

api_version: 1.1
data_provider: FlyBase
data_version: FB2011_01

chado:
   driver: Pg
   hostname: localhost
   database: FB2011_01
   username: jogoodma
   password:
   port: 5432

providers:
   v1_1:
       organism: Bio::GMOD::RPC::v1_1::Organism::FlyBaseOrganisms
       cv: Bio::GMOD::RPC::v1_1::Cv::ChadoCv
       name: Bio::GMOD::RPC::v1_1::Name::ChadoNameResolver
       #go: Bio::GMOD::RPC::v1_1::Ontology::ChadoGO

sql:
    v1_1:
        fetch_by_gene_name: sql/v1_1/fetch_by_gene_name.sql
        fetch_by_go: sql/v1_1/fetch_by_go.sql
        fetch_by_go_not: sql/v1_1/fetch_by_go_not.sql
