charset: utf-8
template: "template_toolkit"
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'
        ENCODE: utf8

#logger: "Log4perl"
#log4perl_conf: log4perl.conf

supported_versions:
   - 1.1

api_version: 1.1
data_provider: FlyBase
data_version: FB2010_07

chado:
   driver: Pg
   hostname: flybase.org
   database: flybase
   username: flybase
   password:
   port: 5432

providers:
   v1_1:
       organism: Bio::GMOD::RPC::v1_1::Organism::FlyBaseOrganisms
       cv: Bio::GMOD::RPC::v1_1::Cv::ChadoCv
       name: Bio::GMOD::RPC::v1_1::Name::ChadoNameResolver
